name: build and test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        working-directory: ./
        run: dotnet restore
      - name: Build
        working-directory: ./
        run: dotnet build --configuration Release --no-restore
      - name: CDK Unit Tests
        working-directory: ./tests/IaC.UnitTests
        run: dotnet test --no-restore --logger GitHubActions
      - name: Core Common Unit Tests
        working-directory: ./tests/Core.Common.UnitTests
        run: dotnet test --no-restore --logger GitHubActions
      - name: Core Storage Unit Tests
        working-directory: ./tests/Core.Storage.UnitTests
        run: dotnet test --no-restore --logger GitHubActions
      - name: Lambda AddTransaction Unit Tests
        working-directory: ./tests/Lambda.AddTransaction.UnitTests
        run: dotnet test --no-restore --logger GitHubActions
      - name: Lambda GetTransaction Unit Tests
        working-directory: ./tests/Lambda.GetTransaction.UnitTests
        run: dotnet test --no-restore --logger GitHubActions
      - name: Lambda DeleteTransaction Unit Tests
        working-directory: ./tests/Lambda.DeleteTransaction.UnitTests
        run: dotnet test --no-restore --logger GitHubActions
      - name: Lambda UpdateTransaction Unit Tests
        working-directory: ./tests/Lambda.UpdateTransaction.UnitTests
        run: dotnet test --no-restore --logger GitHubActions
      - name: Lambda Configuration Unit Tests
        working-directory: ./tests/Lambda.Configuration.UnitTests
        run: dotnet test --no-restore --logger GitHubActions